name: lint with pyright
on:
  [push, pull_request]
jobs:
  pyright:
    name: lint with pyright
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install .
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: get pyright
        run: npm install -g pyright
      - name: pyright
        run: pyright

