name: lint with flake8
on:
  [push, pull_request]
jobs:
  pyright:
    name: lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8
          pip install .
      - name: get flake8
        run: |
          python3 -m pip install flake8
      - name: flake8
        run: flake8

